// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vabpctsrrjshndnnawqy.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYnBjdHNycmpzaG5kbm5hd3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwMzMwODYsImV4cCI6MjA0NjYwOTA4Nn0.J2ZbgC_UBgAl3dj7y3kuNQg90VWKko4RfsisL7fXJIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);