// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://avltzpehyybfzfxzcipc.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bHR6cGVoeXliZnpmeHpjaXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3OTIyNzcsImV4cCI6MjA0NjM2ODI3N30.1lB-O0ilW81JvzBHkuSgsetJh3ciq-CoR-xxjwOnbVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);